# NumPy

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
lst =[1,2,3,4,5,6,7,8,9,10]
%timeit [i**2 for i in lst]

2.84 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
arr=np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
%timeit arr**2

544 ns ± 7.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
#np.array()   np.arange()

#.ndim ->    property of dimensions
#.shape ->   3 X 3

In [19]:
lst2d=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [20]:
arr2d=np.array(lst2d)

In [21]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
arr2d.shape

(4, 3)

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Indexing

In [35]:
np.random.randint(10,100)

38

In [36]:
newArr=np.random.randint(10,100,(5,4))
newArr

array([[67, 36, 58, 64],
       [88, 51, 73, 63],
       [28, 27, 18, 50],
       [23, 65, 37, 89],
       [27, 63, 82, 10]])

In [38]:
newArr[0,3] #or newArr[0][3]
newArr[0][3]

64

## Array Slicing

In [39]:
newArr[2:5, 1:4]

array([[27, 18, 50],
       [65, 37, 89],
       [63, 82, 10]])

In [42]:
newArr[: ,2] #third column only

array([58, 73, 18, 37, 82])

In [43]:
newArr[2:5, 1:4]=0

In [47]:
newArr

array([[67, 36, 58, 64],
       [88, 51, 73, 63],
       [28,  0,  0,  0],
       [23,  0,  0, 99],
       [27,  0,  0,  0]])

In [46]:
newArr[3,3]=99

In [50]:
#masking
mask= newArr > 50
mask

array([[ True, False,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [51]:
np.sum(mask) #-> how many boolean true valuues are there 

8

In [52]:
newArr[mask] #-> all the values satifying the marks 

array([67, 58, 64, 88, 51, 73, 63, 99])

## Matrix Multiplication

In [53]:
A=np.random.randint(10,100,(3,4))
B=np.random.randint(10,100,(4,2))

In [54]:
A

array([[18, 64, 38, 42],
       [89, 86, 35, 79],
       [91, 53, 47, 22]])

In [55]:
B

array([[52, 49],
       [60, 52],
       [66, 63],
       [17, 98]])

In [56]:
np.dot(A,B)

array([[ 7998, 10720],
       [13441, 18780],
       [11388, 12332]])

## Other Operation

In [58]:
np.std(A)

24.920986247649903

In [59]:
np.max(A) 

91

In [60]:
np.sum(A)

664

In [61]:
A

array([[18, 64, 38, 42],
       [89, 86, 35, 79],
       [91, 53, 47, 22]])

In [62]:
np.sum(A, axis=0)
# Column Wise 3,4 shape 0
#  ==> 3rd axis vanished
#   => 4 records will be there

array([198, 203, 120, 143])

In [63]:
np.mean(A, axis=1)
#Row Wise Mean

array([40.5 , 72.25, 53.25])

## Shape Manipulation

In [64]:
A

array([[18, 64, 38, 42],
       [89, 86, 35, 79],
       [91, 53, 47, 22]])

In [65]:
A.flatten()

array([18, 64, 38, 42, 89, 86, 35, 79, 91, 53, 47, 22])

In [66]:
A.reshape(2,6)

array([[18, 64, 38, 42, 89, 86],
       [35, 79, 91, 53, 47, 22]])

In [67]:
A.reshape(2,2,3)

array([[[18, 64, 38],
        [42, 89, 86]],

       [[35, 79, 91],
        [53, 47, 22]]])

In [69]:
A.T
#transpose np.transpose(A)==A.T

array([[18, 89, 91],
       [64, 86, 53],
       [38, 35, 47],
       [42, 79, 22]])

In [70]:

a=np.random.randint(1,10,(2,2))
b=np.random.randint(1,10,(2,2))

In [72]:
##Stacking 
np.hstack((a,b))
#horizontal Stacking

array([[7, 9, 8, 6],
       [7, 3, 3, 1]])

In [73]:
np.vstack((a,b))

array([[7, 9],
       [7, 3],
       [8, 6],
       [3, 1]])

In [75]:
def distance(p1,p2):
    np.sqrt(np.sum(((p1-p2)**2))) #eucliean distance or displacement